### PR TITLE
feat: Avoid close Tags drawer on edit

### PR DESCRIPTION
**Pull request by ChrisChV**
## Description

- To avoid lose user data
- Wrap with ContentTagsDrawerSheet to build drawer on MFE

## Supporting information

- Github issue: https://github.com/openedx/modular-learning/issues/209
- This PR doesn't include:
> The footer of the drawer animates to draw the user's attention to the actions (see [Figma](https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP?type=design&node-id=13585-6449&mode=design&t=hgTeNriivLM74TtO-4)). Perhaps like [Blink 2 at this link](https://webcode.tools/css-generator/keyframe-animation)
- Internal ticket: [FAL-3711](https://tasks.opencraft.com/browse/FAL-3711)
- Depends on: https://github.com/openedx/frontend-app-course-authoring/pull/939

## Testing instructions

- Use this branch of edx-platform: https://github.com/openedx/edx-platform/pull/34490
- Run `make requirements` on cms shell.
- Make sure you have some sample taxonomy/tags data setup: https://github.com/open-craft/taxonomy-sample-data
- Go into a course and click on "Manage tags" option for any unit/block to open the tags drawer
- Click on `Edit tags`
- Delete a tags and verify that can't close drawer when clicking outside.
- Cancel and verify that you can close drawer when clicking outside.
- Click on `Edit tags`
- Add new tags and verify that can't close drawer when clicking outside.

### CODE REVIEW

**Review by yusuf-musleh — COMMENTED** [review]
@ChrisChV Great work on this, the code looks good to me and it works well!

However I am still able to close the drawer when pressing escape even when there are unsaved changes. It might be worth adding some logic to the keypress handler to prevent it from closing when there are unsaved changes.

**Comment by ChrisChV** [comment]
@yusuf-musleh Thanks for the review!

> However I am still able to close the drawer when pressing escape even when there are unsaved changes. It might be worth adding some logic to the keypress handler to prevent it from closing when there are unsaved changes.

Thanks for catch that! I fixed that here: https://github.com/open-craft/frontend-app-course-authoring/pull/34/commits/f4d7e046c1bc3841aea6a6095b5ee3593627831c

**Review by yusuf-musleh — APPROVED** [review]
:+1: @ChrisChV  Great work! Thanks for addressing the issue, its working as expected. For the codecov issue that is failing in the CI, sometimes it gets fixed when re-triggering the CI to run again, I usually do that by doing `git commit --amend --noedit` and then force pushing, it makes no changes to the code, just changes the commit hash because we are amending (nothing) to it.

- [X] I tested this: Followed testing instructions
- [X] I read through the code
- [X] I checked for accessibility issues
- [ ] ~Includes documentation~

**Comment by ChrisChV** [comment]
Close in favor of https://github.com/openedx/frontend-app-course-authoring/pull/965

**Comment by ChrisChV** [comment]
Close in favor of https://github.com/openedx/frontend-app-course-authoring/pull/965

**Pull request closed without merging**
